# Model configuration
model_version: 'v1'  # Only v1 is supported currently
pretrained_weights: null  # Path to pretrained weights if any

# Data configuration
data_root: '../data/dl_challenge'  # Path to dataset directory
train_val_split: 0.8  # Ratio of data to use for training
num_points: 20000  # Number of points per frustum
rotate_to_center: false  # Whether to rotate frustums to face forward
random_flip: false  # Whether to randomly flip data during training
random_shift: false  # Whether to randomly shift points during training

# Training configuration
batch_size: 16
num_epochs: 10
learning_rate: 0.001
weight_decay: 0.0001
lr_step_size: 20
lr_gamma: 0.1
num_workers: 4

# Loss weights
center_weight: 1.0
size_weight: 1.0
heading_weight: 1.0
mask_weight: 1.0

# Hardware configuration
device: 'cuda'  # 'cuda' or 'cpu'

# Output configuration
output_dir: 'runs/frustum_training' 